name: CI for xUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      # Step 3: Clean and restore dependencies
      - name: Clean and restore dependencies
        run: |
          dotnet clean
          dotnet restore

      # Step 4: Build the solution
      - name: Build the solution
        run: dotnet build --configuration Release

      # Step 5: Run the tests
      - name: Run tests
        run: dotnet test --configuration Release --verbosity normal
