name: CI for xUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      # Step 3: Clean previous builds
      - name: Clean build artifacts
        run: dotnet clean

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 5: Build the solution
      - name: Build the solution
        run: dotnet build --configuration Release

      # Step 6: Run xUnit tests
      - name: Run xUnit tests
        run: dotnet test --configuration Release --verbosity normal
