name: CI for xUnit Tests with Versioning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      # Step 3: Clear NuGet cache
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 5: Install GitVersion
      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      # Step 6: Generate version using GitVersion
      - name: Generate version
        id: gitversion
        run: gitversion /output json /showvariable FullSemVer
        shell: bash

      # Step 7: Build the solution with generated version
      - name: Build the solution
        run: dotnet build --configuration Release -p:Version=${{ steps.gitversion.outputs.FullSemVer }}

      # Step 8: Run the tests
      - name: Run tests
        run: dotnet test tests/ReferenceManager.Tests/ReferenceManager.Tests.csproj --configuration Release --verbosity normal
