name: Code Coverage and Badge

on:
  push:
    branches:
      - codecov
  pull_request:

jobs:
  run-tests-and-generate-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      - name: Clean Build Cache
        run: dotnet clean --verbosity normal

      - name: Restore dependencies
        run: dotnet restore

      - name: Confirm Installed Versions
        run: dotnet list tests/ReferenceManager.Tests/ReferenceManager.Tests.csproj package

      - name: Run tests with coverage and diagnostics
        run: |
          dotnet test --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          -p:CollectCoverage=true \
          -p:CoverletOutputFormat=cobertura \
          -p:CoverletOutput=./TestResults/coverage.cobertura.xml \
          --diag:TestExecution.log
